const apiErrorSchema = require('./src/docs/schemas/apiError.schema.ts');
const swaggerAutogen = require('swagger-autogen')({ openapi: '3.0.0' });
const tags = require('./src/docs/tags.ts');
const tokenSchema = require('./src/docs/schemas/token.schema.ts');
const userSchema = require('./src/docs/schemas/user.schema.ts');
const productSchema = require('./src/docs/schemas/product.schema.ts');

const doc = {
  info: {
    version: '1.0.0',
    title: 'Elyte Store API',
    description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.'
  },
  servers: [
    {
      url: 'http://localhost:3000',
      description: 'Local server'
    }
  ],
  tags: tags,
  securityDefinitions: {
    Bearer: {
      type: 'apiKey',
      in: 'header',
      name: 'Authorization',
      description: 'Enter your bearer token in the format **Bearer &lt;token>**'
    }
  },
  components: {
    schemas: {
      Token: tokenSchema,
      User: userSchema,
      Product: productSchema,
      ApiError: apiErrorSchema
    }
  }
};

const outputFile = './swagger-output.json';
const endPointsFolder = ['./src/app.ts'];

void swaggerAutogen(outputFile, endPointsFolder, doc);
